### ISSUE TITLE
Add instructions to generate certificates

### ISSUE THREAD

**Issue by MiguelRipoll23** [nategood/node-auth#3]
I'd be great if there were instructions on the `README.md` file to generate the keys and certificates.

**Comment by MiroRadenovic** [comment]
+1

**Comment by nkint** [comment]
+1

**Comment by adrai** [comment]
any progress on this?

**Comment by nategood** [comment]
I'm open to a pull request. There are many places on the web that already
outline this process.

**Comment by coolaj86** [comment]
I've got some here: https://github.com/coolaj86/nodejs-self-signed-certificate-example

and here: https://github.com/coolaj86/node-ssl-root-cas/wiki/Painless-Self-Signed-Certificates-in-node.js

**Comment by coolaj86** [comment]
I was able to figure out how to modify my existing example to work with the example in this repo. Here's my updated examples:

https://github.com/coolaj86/nodejs-ssl-trusted-peer-example

**Comment by MiguelRipoll23** [comment]
@colaj86 Great job, man.

**Comment by MiroRadenovic** [comment]
@coolaj86  thx so much
